Feature/graceful error handling
navikt/dolly-frontend pull request #30
Opened 2020-09-14 07:40 UTC by stigus

2020-09-14 12:38 UTC, langvatn requested changes
Ser greit ut er bare ikke så genersik som jeg øsnket.

2020-09-14 12:38 UTC, langvatn commented on src/main/web_src/src/components/fagsystem/inntektsmelding/form/partials/InntektsmeldingSelect.tsx
> +				return <ErrorComponent errorMessage={error} feilKomponent={'InntektsmeldingSelect'} />
Kan skrives simplere med:
```
renderOnError={error => (
  <ErrorComponent errorMessage={error} feilKomponent={'InntektsmeldingSelect'} />
)}
render={data: Array<Option> => (
  <FormikSelect name={path} label={label} options={data} type="text" size={size} />
)}
```

2020-09-14 12:38 UTC, langvatn commented on src/main/web_src/src/components/fagsystem/inntektsmelding/form/partials/InntektsmeldingSelect.tsx
> +import { ErrorComponent } from '~/components/ui/loading/ErrorComponent'
Kan du finne på et bedre navn?

2020-09-14 12:38 UTC, langvatn commented on src/main/web_src/src/components/journalpostid/JournalpostidVisning.tsx
> +			return <ErrorComponent errorMessage={error} feilKomponent={'JournalpostidVisning'} />
feilKomponent={'JournalpostidVisning'} skal du kunne hente ut uten å måtte sende den inn. På den måten sliper du å altid skrive samme kodelinje:
`<ErrorComponent errorMessage={error} feilKomponent={'xzy'} />`

Worst case ville jeg ha sendt den inn i loadable component.

Kontakt meg for å vite hvordan

2020-09-14 12:48 UTC, stigus commented on src/main/web_src/src/components/fagsystem/inntektsmelding/form/partials/InntektsmeldingSelect.tsx
> +import { ErrorComponent } from '~/components/ui/loading/ErrorComponent'
Haha, skal prøve

2020-09-21 11:03 UTC, langvatn commented on src/main/web_src/src/components/ui/loading/LoadableComponent.tsx
> +					uuid: uuid // UUID her og i render er forskjellige?
Logger.error (Husker jeg riktig?) skal allerede sett Uuid hvis den ikke er satt og siden du uansett setter den vær gang så er det ikke vists å gjøre det dirkte.

2020-09-21 11:03 UTC, langvatn commented on src/main/web_src/src/components/ui/loading/DollyErrorAlert.tsx
> +			UUID: {uuid}
Denne uuid gir oss ikke noe info fra frontend. I fremtiden burde vi heller vise azure_id en

2020-09-21 11:04 UTC, langvatn commented on src/main/web_src/src/components/ui/loading/DollyErrorAlert.tsx
> +			UUID: {uuid}
Med andre ord bare fjern den

2020-09-21 11:59 UTC, langvatn approved these changes
Supert 👍

2020-09-28 14:24 UTC, betsytraran approved these changes
Hadde en liten kommentar, ellers ser det supert ut 😄

2020-09-28 14:24 UTC, betsytraran commented on src/main/web_src/src/components/organisasjonSelect/OrganisasjonLoader.tsx
> +			<LoadableComponent onFetch={onFetch} render={(list: Organisasjon[]) => render(list)} />
Jeg fikk en 500-feil på henting av organisasjoner, men da fikk jeg ingen error i GUI, kun en tom liste. Vil du sjekke om du får det til å fungere hos deg? 😄

2020-09-29 06:50 UTC, stigus commented on src/main/web_src/src/components/organisasjonSelect/OrganisasjonLoader.tsx
> +			<LoadableComponent onFetch={onFetch} render={(list: Organisasjon[]) => render(list)} />
Ojda, bra du fant 👍 Har bare testa i arbeidsforhold og synt-sykemelding og da får jeg tilbake riktig liste og uten feil 😅 Skal teste litt videre 😄

2020-10-02 15:51 UTC, betsytraran commented on src/main/web_src/src/components/organisasjonSelect/OrganisasjonLoader.tsx
> +			<LoadableComponent onFetch={onFetch} render={(list: Organisasjon[]) => render(list)} />
Beklager, så ikke kommentaren din før nå! 😅 Men bra du fant ut av det - nå blir det veldig bra 😄

2020-10-06 12:18 UTC, merged